//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public long bitacora_id { get; set; }
        public System.DateTime date { get; set; }
        public string origin { get; set; }
        public string message { get; set; }
        public long user_id { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
