//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant_tags
    {
        public long restaurant_tag_id { get; set; }
        public long tag_id { get; set; }
        public long restaurant_id { get; set; }
    
        public virtual Restaurants Restaurants { get; set; }
        public virtual Tags Tags { get; set; }
    }
}
