//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CGAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reviews()
        {
            this.Review_requests = new HashSet<Review_requests>();
        }
    
        public long review_id { get; set; }
        public decimal rating { get; set; }
        public string review_content { get; set; }
        public System.DateTime review_date { get; set; }
        public Nullable<bool> is_visible { get; set; }
        public long user_id { get; set; }
        public long restaurant_id { get; set; }
    
        public virtual Restaurants Restaurants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review_requests> Review_requests { get; set; }
        public virtual Users Users { get; set; }
    }
}
